service: aws-node-puppeteer
provider:
  name: aws
  profile: default
  region: eu-north-1
  runtime: nodejs12.x
  iamRoleStatements:
        - Effect: "Allow"
          Action:
              - "s3:upload"
          Resource: "arn:aws:s3:::masoud-user-data-bucket-123/*"

plugins:
  - serverless-offline
  - serverless-plugin-chrome


  
package:
  exclude:
    - node_modules/puppeteer/.local-chromium/**
functions:
  hello:
    handler: handler.hello
    memorySize: 1536MB
    timeout: 30
    events:
      - http:
          path: /
          method: get
    layers:
      - layerArn 
          